services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-api
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/app
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      SERVER_PORT: 8080
    volumes:
      - media_storage:/app/storage
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: springboot-db
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  media_storage:
